### ISSUE TITLE
rvehicle doesn't work without argument

### ISSUE THREAD

**Issue by Quenntinne** [BlackLotusLV/LiveBot#5]
I've try the command rvehicle without arguments and it doesn't work.
But I've see in the code there is a "if" if the user doesn't send an argument.
You should probably change the 
`            if (discipline == null)
            {
                disciplinename = "Street Race";
            }`

by 
`            if (discipline == null)
            {
                disciplinename = "449688867164127232"; // ID of the street race emoji
            }`

**Comment by BlackLotusLV** [comment]
No, found the issue - it sent an error when trying to see the id of the emoji while it was null. Simply had to put the switch in else{} and it fixed it.
